"""
Arkadia Knowledge OS — Canonical Relationship Type Registry
===========================================================
Single source of truth for all relationship types used in the Knowledge Graph.

LAW I: One capability. One implementation. One canonical home.

Constitutional spec: docs/KNOWLEDGE_GRAPH_SPEC.md

Do NOT define RELATIONSHIP_TYPES anywhere else in the repository.
vault.py, graph.py, pipeline.py, and all subsystems import from here.
"""

from dataclasses import dataclass
from typing import Literal


# ─────────────────────────────────────────────────────────────────────────────
# Relationship type definition
# ─────────────────────────────────────────────────────────────────────────────

Direction = Literal["directed", "undirected"]


@dataclass(frozen=True)
class RelationshipDef:
    """Canonical definition of a knowledge graph relationship."""
    identifier: str        # snake_case key used in graph_edges rows
    display_name: str      # Human-readable label
    direction: Direction   # directed (A→B has meaning) or undirected (A↔B)
    description: str       # What it means when A has this relationship to B


# ─────────────────────────────────────────────────────────────────────────────
# Canonical registry
# Every relationship that can appear in a graph_edges row must be defined here.
# ─────────────────────────────────────────────────────────────────────────────

RELATIONSHIP_REGISTRY: dict[str, RelationshipDef] = {
    r.identifier: r for r in [

        # ── Authorship / Provenance ───────────────────────────────────────────
        RelationshipDef(
            identifier="created",
            display_name="Created",
            direction="directed",
            description="A was originally created by agent or person B.",
        ),
        RelationshipDef(
            identifier="authored_by",
            display_name="Authored By",
            direction="directed",
            description="A was written or composed by person B.",
        ),
        RelationshipDef(
            identifier="generated",
            display_name="Generated",
            direction="directed",
            description="A was produced by a system or process B.",
        ),
        RelationshipDef(
            identifier="generated_by",
            display_name="Generated By",
            direction="directed",
            description="A was produced by system or agent B (inverse of 'generated').",
        ),
        RelationshipDef(
            identifier="reviewed_by",
            display_name="Reviewed By",
            direction="directed",
            description="A was evaluated or approved by B.",
        ),

        # ── Semantic / Epistemic ──────────────────────────────────────────────
        RelationshipDef(
            identifier="references",
            display_name="References",
            direction="directed",
            description="A cites or points to B as a source or related item.",
        ),
        RelationshipDef(
            identifier="derived_from",
            display_name="Derived From",
            direction="directed",
            description="A is built on or sourced from B.",
        ),
        RelationshipDef(
            identifier="contradicts",
            display_name="Contradicts",
            direction="undirected",
            description="A directly opposes or refutes B.",
        ),
        RelationshipDef(
            identifier="supported_by",
            display_name="Supported By",
            direction="directed",
            description="A is validated or corroborated by B.",
        ),
        RelationshipDef(
            identifier="inspired",
            display_name="Inspired",
            direction="directed",
            description="A creatively motivated or gave rise to B.",
        ),
        RelationshipDef(
            identifier="inspired_by",
            display_name="Inspired By",
            direction="directed",
            description="A was creatively motivated by B.",
        ),
        RelationshipDef(
            identifier="mentions",
            display_name="Mentions",
            direction="directed",
            description="A contains a surface-level reference to B without deep dependency.",
        ),
        RelationshipDef(
            identifier="relates_to",
            display_name="Relates To",
            direction="undirected",
            description="Catch-all semantic connection between A and B.",
        ),
        RelationshipDef(
            identifier="connected_to",
            display_name="Connected To",
            direction="undirected",
            description="A and B are associated; directionality is not semantically meaningful.",
        ),

        # ── Structural / Hierarchical ─────────────────────────────────────────
        RelationshipDef(
            identifier="belongs_to",
            display_name="Belongs To",
            direction="directed",
            description="A is a member of collection or category B.",
        ),
        RelationshipDef(
            identifier="member_of",
            display_name="Member Of",
            direction="directed",
            description="A is a member of group, community, or organisation B.",
        ),
        RelationshipDef(
            identifier="part_of",
            display_name="Part Of",
            direction="directed",
            description="A is a sub-element or component of B.",
        ),
        RelationshipDef(
            identifier="child_of",
            display_name="Child Of",
            direction="directed",
            description="A descends from B in a hierarchy.",
        ),
        RelationshipDef(
            identifier="parent_of",
            display_name="Parent Of",
            direction="directed",
            description="A contains B as a child element.",
        ),
        RelationshipDef(
            identifier="follows",
            display_name="Follows",
            direction="directed",
            description="A comes after B in a sequence or timeline.",
        ),
        RelationshipDef(
            identifier="precedes",
            display_name="Precedes",
            direction="directed",
            description="A comes before B in a sequence or timeline.",
        ),

        # ── Usage / Dependency ────────────────────────────────────────────────
        RelationshipDef(
            identifier="uses",
            display_name="Uses",
            direction="directed",
            description="A employs or consumes B as a tool, resource, or dependency.",
        ),
        RelationshipDef(
            identifier="owns",
            display_name="Owns",
            direction="directed",
            description="A has authority over or possesses B.",
        ),
        RelationshipDef(
            identifier="depends_on",
            display_name="Depends On",
            direction="directed",
            description="A cannot function or proceed without B.",
        ),

        # ── Discourse / Conversation ──────────────────────────────────────────
        RelationshipDef(
            identifier="replies_to",
            display_name="Replies To",
            direction="directed",
            description="A is a direct response to B in a conversation or thread.",
        ),

        # ── Transformation / Extension ────────────────────────────────────────
        RelationshipDef(
            identifier="extends",
            display_name="Extends",
            direction="directed",
            description="A builds upon or expands the scope of B.",
        ),
        RelationshipDef(
            identifier="summarizes",
            display_name="Summarizes",
            direction="directed",
            description="A is a condensed or abstract version of B.",
        ),
        RelationshipDef(
            identifier="implements",
            display_name="Implements",
            direction="directed",
            description="A is a concrete realisation of the specification or concept B.",
        ),
    ]
}

# ─────────────────────────────────────────────────────────────────────────────
# Backward-compatible list and set for validation
# Use RELATIONSHIP_TYPES for list iteration.
# Use RELATIONSHIP_TYPES_SET for O(1) membership checks.
# ─────────────────────────────────────────────────────────────────────────────

RELATIONSHIP_TYPES: list[str] = list(RELATIONSHIP_REGISTRY.keys())
RELATIONSHIP_TYPES_SET: frozenset[str] = frozenset(RELATIONSHIP_TYPES)


def validate_relationship(relationship: str) -> bool:
    """Return True if relationship is in the canonical registry. Does not raise."""
    return relationship in RELATIONSHIP_TYPES_SET
